### ISSUE TITLE
Is DeployStructLib.Parts.Cloth.Initializers.Cloth_Mass_initializer missing?

### ISSUE THREAD

**Issue by beutlich** [ATAEngineering/DeployStructLib#7]
DeployStructLib.Parts.Cloth.Initializers.Cloth_Mass_initializer is referenced, but not found. Should it be Cloth_MassLoc_initializer?

**Comment by crupp2** [comment]
That may be an artifact of some changes I made a long time ago before moving to git. I've been thinking about simplifying/cleaning up some of the cloth, so let me revisit this.

**Comment by crupp2** [comment]
I've finished simplifying the cloth block. There was a bunch of historical stuff in there that was no longer needed. It should be easier to understand (hopefully) and maintain (hopefully).
